p = int (input ())
x = int (input ())
y = int (input ())
h = 1 + (p / 100)
n = round (h * y)
k = round (x * h)
a = round (k + (h * y) // 100)
b = round (((x * h) - k) * 100 + n % 100)
print (a, b)